apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-app-nodejs
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: mon-app-nodejs
  template:
    metadata:
      labels:
        app: mon-app-nodejs
    spec:
      containers:
      - name: nodejs-container
        image: malekghorbel/monappnodejs:latest
        ports:
        - containerPort: 80  
